[CHECKOUTUI-106] Allow customization of InStore checkout files via admin when using Checkout UI Custom app
vtex-apps/checkout-ui-settings-server pull request #43
Opened 2022-09-02 21:30 UTC by AnnaChiu95

#### What does this PR do? 
When [vtex.checkout-ui-custom](https://github.com/vtex-apps/checkout-ui-custom) or [vtex.checkout-ui-settings](https://github.com/vtex-apps/checkout-ui-settings) is installed in a workspace, the checkout files saved in the admin will no longer apply. This PR enables users to edit and apply InStore checkout files (checkout-instore-custom.css and checkout-instore-custom.js) in the admin for workspaces with `vtex.checkout-ui-custom` installed.

#### How to test it? 
Test in workspace [annacheckout](https://annacheckout--sandboxusdev.myvtex.com/admin).

Here's a [cart link](https://annacheckout--sandboxusdev.myvtex.com/checkout/cart/add/?sku=2&qty=1&seller=1&sc=1). Go to Inspect > Sources and view the checkout files. For this workspace, I mimicked the scenario using a custom version of `vtex.checkout-ui-settings` and enabled users to edit checkout6-custom.css via the admin while the checkout6-custom.js content comes from the checkout-ui-settings app.

_checkout6-custom.css using [admin content](https://annacheckout--sandboxusdev.myvtex.com/admin/portal/#/sites/default/code/files/checkout6-custom.css)_
<img width="1440" alt="Screen Shot 2022-09-02 at 5 27 10 PM" src="https://user-images.githubusercontent.com/53097865/188237593-1a29e5b4-68ec-4855-a32d-6fd2ffd2ee53.png">

_checkout6-custom.js not using [admin content](https://annacheckout--sandboxusdev.myvtex.com/admin/portal/#/sites/default/code/files/checkout6-custom.js)_
<img width="1439" alt="Screen Shot 2022-09-02 at 5 19 36 PM" src="https://user-images.githubusercontent.com/53097865/188237124-ac569215-f116-4099-a91a-6e22568bea2f.png">

2022-09-06 17:52 UTC, polishq requested changes

2022-09-06 17:52 UTC, polishq commented on node/clients/portalFiles.ts
> +                VtexIdclientAutCookie: ctx.adminUserAuthToken ?? ctx.authToken,
I would use `ctx.authToken` in all cases, as we have control over the app's permissions but the user's can vary

2022-09-06 19:59 UTC, AnnaChiu95 commented on node/clients/portalFiles.ts
> +export default class PortalFiles extends ExternalClient{
Ok, I switched to `JanusClient`. I was previously getting 403 errors so I thought it had something to do with the client but now I see that it was really an issue with `ctx.authToken`

2022-09-07 13:43 UTC, AnnaChiu95 commented on node/clients/portalFiles.ts
> +                VtexIdclientAutCookie: ctx.adminUserAuthToken ?? ctx.authToken,
Done.

2022-09-07 14:46 UTC, polishq approved these changes
LGTM

2022-09-07 15:08 UTC, merged