Improve performance when using checkout-ui-custom
vtex-apps/checkout-ui-settings-server pull request #8
Opened 2021-06-29 23:02 UTC by wender

### Changed
- When using `checkout-ui-custom`, it will first look for files on **VBase**, **Masterdata** is now a fallback

2021-06-30 21:04 UTC, brunoabreu requested changes

2021-06-30 21:04 UTC, brunoabreu commented on node/middlewares/settings.ts
> +        .catch(() => null)
We should at least log something on Splunk.

2021-06-30 21:04 UTC, brunoabreu commented on node/middlewares/settings.ts
> +      const vbFile = await vbase.getFile('checkoutuicustom', `${workspace}-${field}`)
Is it a JSON? Could you use getJSON?

2021-06-30 21:52 UTC, wender commented on node/middlewares/settings.ts
> +      const vbFile = await vbase.getFile('checkoutuicustom', `${workspace}-${field}`)
It's not a JSON, it's either a CSS or a Javascript file

2021-07-01 13:34 UTC, wender commented on node/middlewares/savevb.ts
> +    .saveFile('checkoutuicustom', `${workspace}-${field}`, stream)
it's either a CSS or a Javascript file

2021-07-01 20:07 UTC, brunoabreu approved these changes

2021-07-01 20:33 UTC, merged